//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rectification
    {
        public int RectificationID { get; set; }
        public Nullable<System.DateTime> RectificationDate { get; set; }
        public string RectificationNotes { get; set; }
        public string userID { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
